<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 26,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 27,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 28,
                'data_type_id' => 3,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 29,
                'data_type_id' => 3,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'password',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 30,
                'data_type_id' => 3,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"roles","pivot":"0"}',
                'order' => 10,
            ),
            5 => 
            array (
                'id' => 31,
                'data_type_id' => 3,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'remember_token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 5,
            ),
            6 => 
            array (
                'id' => 32,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 6,
            ),
            7 => 
            array (
                'id' => 33,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 7,
            ),
            8 => 
            array (
                'id' => 34,
                'data_type_id' => 3,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 8,
            ),
            9 => 
            array (
                'id' => 35,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            10 => 
            array (
                'id' => 36,
                'data_type_id' => 5,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre del menú',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            11 => 
            array (
                'id' => 37,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            12 => 
            array (
                'id' => 38,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            13 => 
            array (
                'id' => 46,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            14 => 
            array (
                'id' => 47,
                'data_type_id' => 6,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            15 => 
            array (
                'id' => 48,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            16 => 
            array (
                'id' => 49,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            17 => 
            array (
                'id' => 50,
                'data_type_id' => 6,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            18 => 
            array (
                'id' => 53,
                'data_type_id' => 3,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'role_id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 9,
            ),
            19 => 
            array (
                'id' => 54,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            20 => 
            array (
                'id' => 55,
                'data_type_id' => 8,
                'field' => 'home',
                'type' => 'checkbox',
                'display_name' => 'Home?',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"on":"Sí","off":"No","display":{"width":1}}',
                'order' => 7,
            ),
            21 => 
            array (
                'id' => 56,
                'data_type_id' => 8,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":3}}',
                'order' => 4,
            ),
            22 => 
            array (
                'id' => 57,
                'data_type_id' => 8,
                'field' => 'acceso',
                'type' => 'select_dropdown',
                'display_name' => 'Acceso',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"publico","options":{"publico":"Público","restringido":"Restringido"},"display":{"width":2}}',
                'order' => 8,
            ),
            23 => 
            array (
                'id' => 58,
                'data_type_id' => 8,
                'field' => 'menu_id',
                'type' => 'hidden',
                'display_name' => 'Menu',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 13,
            ),
            24 => 
            array (
                'id' => 59,
                'data_type_id' => 8,
                'field' => 'menu_item_id',
                'type' => 'hidden',
                'display_name' => 'Menu Item',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"null":"","display":{"width":3}}',
                'order' => 15,
            ),
            25 => 
            array (
                'id' => 60,
                'data_type_id' => 8,
                'field' => 'tipo_slider',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo Slider',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"default":"3s","options":{"0":"Sin slider","3s":"Slider completo","3sA":"Slider completo alto","2s+1i":"2+1 (slider+imagen)","2sA+1iA":"2+1 alto (slider+imagen)","3i":"Imagen completa","3s+1i":"3+1 (slider+imagen)"},"display":{"width":4,"id":"tipo_slider"}}',
                'order' => 17,
            ),
            26 => 
            array (
                'id' => 61,
                'data_type_id' => 8,
                'field' => 'columnas_pastillas',
                'type' => 'radio_btn',
                'display_name' => 'Número de columnas de pastillas',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"3","options":{"2":"2 columnas","3":"3 columnas"}}',
                'order' => 22,
            ),
            27 => 
            array (
                'id' => 62,
                'data_type_id' => 8,
                'field' => 'slider_id',
                'type' => 'hidden',
                'display_name' => 'Slider Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4,"id":"slider_id"}}',
                'order' => 18,
            ),
            28 => 
            array (
                'id' => 64,
                'data_type_id' => 8,
                'field' => 'visible',
                'type' => 'checkbox',
                'display_name' => 'Visible',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sí","off":"No","display":{"width":1}}',
                'order' => 5,
            ),
            29 => 
            array (
                'id' => 65,
                'data_type_id' => 8,
                'field' => 'contenido',
                'type' => 'rich_text_box',
                'display_name' => 'Contenido',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 25,
            ),
            30 => 
            array (
                'id' => 66,
                'data_type_id' => 8,
                'field' => 'role_id',
                'type' => 'hidden',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            31 => 
            array (
                'id' => 67,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 31,
            ),
            32 => 
            array (
                'id' => 68,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 32,
            ),
            33 => 
            array (
                'id' => 70,
                'data_type_id' => 8,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'URL de acceso',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":3},"slugify":{"origin":"nombre"}}',
                'order' => 6,
            ),
            34 => 
            array (
                'id' => 71,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_menu_item_relationship',
                'type' => 'relationship',
                'display_name' => 'Miga de Pan',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\MenuItem","table":"menu_items","type":"belongsTo","column":"menu_item_id","key":"id","label":"title","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 16,
            ),
            35 => 
            array (
                'id' => 72,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_menu_relationship',
                'type' => 'relationship',
                'display_name' => 'Menú/sección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Menu","table":"menus","type":"belongsTo","column":"menu_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 14,
            ),
            36 => 
            array (
                'id' => 73,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Propietario',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            37 => 
            array (
                'id' => 74,
                'data_type_id' => 5,
                'field' => 'menu_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Sección',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"acceso_ip","pivot":"0"}',
                'order' => 4,
            ),
            38 => 
            array (
                'id' => 75,
                'data_type_id' => 5,
                'field' => 'role_id',
                'type' => 'hidden',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            39 => 
            array (
                'id' => 76,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            40 => 
            array (
                'id' => 77,
                'data_type_id' => 10,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            41 => 
            array (
                'id' => 78,
                'data_type_id' => 10,
                'field' => 'tipo',
                'type' => 'select_dropdown',
                'display_name' => 'Tipo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"imagen","options":{"imagen":"Imagen","boton":"Botón","rrss":"Redes Sociales"},"display":{"width":3},"description":"Redes sociales son las que aparecen en la cabecera! Solo para usuarios de la sección institucional."}',
                'order' => 9,
            ),
            42 => 
            array (
                'id' => 79,
                'data_type_id' => 10,
                'field' => 'formato',
                'type' => 'select_dropdown',
                'display_name' => 'Formato',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"default":"s-3","options":{"s-3":"Slider, imagen completa (1140x240)","s-3A":"Slider alto, imagen completa (1140x300)","s-2":"Slider, imagen 2/3 (750x240)","s-2A":"Slider alto, imagen 2/3 (750x300)","s-1":"Slider, imagen 1/3 (360x240)","s-1A":"Slider alto, imagen 1/3 (360x300)","s-4":"Slider, imagen 3/4 (847x300)","s-14":"Slider, imagen 1/4 (263x300)","p-3":"Pastilla (360x235)","p-3-doble":"Pastilla, altura doble (360x500)","p-2":"Pastilla grande (555x300)","p-2-doble":"Pastilla grande, altura doble (555x630)","0:0":"Formato libre"},"display":{"width":4}}',
                'order' => 10,
            ),
            43 => 
            array (
                'id' => 80,
                'data_type_id' => 10,
                'field' => 'publica',
                'type' => 'checkbox',
                'display_name' => 'Pública?',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"on":"Sí","off":"No","display":{"width":1},"description":"Visible y utilizable por todos los usuarios (solo modificable por usuarios de tu sección)."}',
                'order' => 11,
            ),
            44 => 
            array (
                'id' => 81,
                'data_type_id' => 10,
                'field' => 'role_id',
                'type' => 'hidden',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4}}',
                'order' => 2,
            ),
            45 => 
            array (
                'id' => 82,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 15,
            ),
            46 => 
            array (
                'id' => 83,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 16,
            ),
            47 => 
            array (
                'id' => 84,
                'data_type_id' => 10,
                'field' => 'partesgrafica_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Propietario',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"calendario","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            48 => 
            array (
                'id' => 85,
                'data_type_id' => 10,
                'field' => 'imagen',
                'type' => 'image',
                'display_name' => 'Imagen',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 14,
            ),
            49 => 
            array (
                'id' => 86,
                'data_type_id' => 10,
                'field' => 'created_by_id',
                'type' => 'hidden',
                'display_name' => 'Creado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            50 => 
            array (
                'id' => 87,
                'data_type_id' => 10,
                'field' => 'updated_by_id',
                'type' => 'hidden',
                'display_name' => 'Actualizado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            51 => 
            array (
                'id' => 88,
                'data_type_id' => 10,
                'field' => 'partesgrafica_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Creado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_by_id","key":"id","label":"name","pivot_table":"calendario","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            52 => 
            array (
                'id' => 89,
                'data_type_id' => 10,
                'field' => 'partesgrafica_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Actualizado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_by_id","key":"id","label":"name","pivot_table":"calendario","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            53 => 
            array (
                'id' => 90,
                'data_type_id' => 8,
                'field' => 'created_by_id',
                'type' => 'hidden',
                'display_name' => 'Created By Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            54 => 
            array (
                'id' => 91,
                'data_type_id' => 8,
                'field' => 'updated_by_id',
                'type' => 'hidden',
                'display_name' => 'Updated By Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 11,
            ),
            55 => 
            array (
                'id' => 92,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Creada por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_by_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            56 => 
            array (
                'id' => 93,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Actualizado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_by_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 12,
            ),
            57 => 
            array (
                'id' => 104,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            58 => 
            array (
                'id' => 105,
                'data_type_id' => 12,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4}}',
                'order' => 4,
            ),
            59 => 
            array (
                'id' => 106,
                'data_type_id' => 12,
                'field' => 'formato',
                'type' => 'select_dropdown',
                'display_name' => 'Formato',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"p-3":"3 columnas","p-3-doble":"3 columnas, doble","p-2":"2 columnas","p-2-doble":"2 columnas, doble"},"display":{"width":3}}',
                'order' => 9,
            ),
            60 => 
            array (
                'id' => 107,
                'data_type_id' => 12,
                'field' => 'texto',
                'type' => 'rich_text_box',
                'display_name' => 'Cuerpo',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 14,
            ),
            61 => 
            array (
                'id' => 108,
                'data_type_id' => 12,
                'field' => 'texto_cabecera',
                'type' => 'text',
                'display_name' => 'Título de la pastilla',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":5}}',
                'order' => 10,
            ),
            62 => 
            array (
                'id' => 109,
                'data_type_id' => 12,
                'field' => 'enlace',
                'type' => 'text',
                'display_name' => 'Enlace',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":7}}',
                'order' => 11,
            ),
            63 => 
            array (
                'id' => 110,
                'data_type_id' => 12,
                'field' => 'destino_enlace',
                'type' => 'select_dropdown',
                'display_name' => 'Destino Enlace',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Por defecto":"Por defecto","Popup":"Pop-up","Nuevo":"Ventana/pestaña nueva"},"display":{"width":4}}',
                'order' => 12,
            ),
            64 => 
            array (
                'id' => 111,
                'data_type_id' => 12,
                'field' => 'role_id',
                'type' => 'hidden',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            65 => 
            array (
                'id' => 112,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 15,
            ),
            66 => 
            array (
                'id' => 113,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 16,
            ),
            67 => 
            array (
                'id' => 114,
                'data_type_id' => 12,
                'field' => 'pastilla_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Propietario',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            68 => 
            array (
                'id' => 115,
                'data_type_id' => 12,
                'field' => 'created_by_id',
                'type' => 'hidden',
                'display_name' => 'Created By Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            69 => 
            array (
                'id' => 116,
                'data_type_id' => 12,
                'field' => 'updated_by_id',
                'type' => 'hidden',
                'display_name' => 'Updated By Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            70 => 
            array (
                'id' => 117,
                'data_type_id' => 12,
                'field' => 'pastilla_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Creado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_by_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            71 => 
            array (
                'id' => 118,
                'data_type_id' => 12,
                'field' => 'pastilla_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Actualizado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_by_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            72 => 
            array (
                'id' => 119,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            73 => 
            array (
                'id' => 120,
                'data_type_id' => 13,
                'field' => 'nombre',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6}}',
                'order' => 8,
            ),
            74 => 
            array (
                'id' => 121,
                'data_type_id' => 13,
                'field' => 'formato',
                'type' => 'select_dropdown',
                'display_name' => 'Formato',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"s-3":"Completo","s-3A":"Completo alto","s-2":"2+1","s-2A":"2+1 alto","s-4":"3+1"},"display":{"width":2}}',
                'order' => 9,
            ),
            75 => 
            array (
                'id' => 122,
                'data_type_id' => 13,
                'field' => 'role_id',
                'type' => 'hidden',
                'display_name' => 'Role Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4}}',
                'order' => 2,
            ),
            76 => 
            array (
                'id' => 123,
                'data_type_id' => 13,
                'field' => 'created_by_id',
                'type' => 'hidden',
                'display_name' => 'Created By Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            77 => 
            array (
                'id' => 124,
                'data_type_id' => 13,
                'field' => 'updated_by_id',
                'type' => 'hidden',
                'display_name' => 'Updated By Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            78 => 
            array (
                'id' => 125,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 10,
            ),
            79 => 
            array (
                'id' => 126,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 11,
            ),
            80 => 
            array (
                'id' => 127,
                'data_type_id' => 13,
                'field' => 'slider_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Propietario',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            81 => 
            array (
                'id' => 128,
                'data_type_id' => 13,
                'field' => 'slider_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Creado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_by_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            82 => 
            array (
                'id' => 129,
                'data_type_id' => 13,
                'field' => 'slider_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Actualizado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_by_id","key":"id","label":"name","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            83 => 
            array (
                'id' => 130,
                'data_type_id' => 13,
                'field' => 'slider_belongstomany_partesgrafica_relationship',
                'type' => 'relationship',
                'display_name' => 'Diapositivas',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Partesgrafica","table":"partesgraficas","type":"belongsToMany","column":"id","key":"id","label":"nombre","pivot_table":"partesgrafica_slider","pivot":"1","taggable":"0"}',
                'order' => 12,
            ),
            84 => 
            array (
                'id' => 131,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_slider_relationship',
                'type' => 'relationship',
                'display_name' => 'Slider',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Slider","table":"sliders","type":"belongsTo","column":"slider_id","key":"id","label":"nombre","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 19,
            ),
            85 => 
            array (
                'id' => 132,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_partesgrafica_relationship',
                'type' => 'relationship',
            'display_name' => 'Imagen (espacio del slider)',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Partesgrafica","table":"partesgraficas","type":"belongsTo","column":"partesgrafica_id","key":"id","label":"nombre","pivot_table":"data_rows","pivot":"0","taggable":"0"}',
                'order' => 21,
            ),
            86 => 
            array (
                'id' => 133,
                'data_type_id' => 8,
                'field' => 'partesgrafica_id',
                'type' => 'hidden',
                'display_name' => 'Partesgrafica Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":4}}',
                'order' => 20,
            ),
            87 => 
            array (
                'id' => 134,
                'data_type_id' => 8,
                'field' => 'pagina_belongstomany_pastilla_relationship',
                'type' => 'relationship',
                'display_name' => 'Pastillas',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Pastilla","table":"pastillas","type":"belongsToMany","column":"id","key":"id","label":"nombre","pivot_table":"pagina_pastilla","pivot":"1","taggable":"0"}',
                'order' => 23,
            ),
            88 => 
            array (
                'id' => 135,
                'data_type_id' => 12,
                'field' => 'pastilla_belongstomany_partesgrafica_relationship',
                'type' => 'relationship',
                'display_name' => 'Imagen/Imágenes',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Partesgrafica","table":"partesgraficas","type":"belongsToMany","column":"id","key":"id","label":"nombre","pivot_table":"partesgrafica_pastilla","pivot":"1","taggable":"0"}',
                'order' => 13,
            ),
            89 => 
            array (
                'id' => 136,
                'data_type_id' => 8,
                'field' => 'pagina_belongstomany_menu_item_relationship',
                'type' => 'relationship',
                'display_name' => 'Destacados',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\MenuItem","table":"menu_items","type":"belongsToMany","column":"id","key":"id","label":"title","pivot_table":"menu_item_pagina","pivot":"1","taggable":"0"}',
                'order' => 24,
            ),
            90 => 
            array (
                'id' => 137,
                'data_type_id' => 8,
                'field' => 'contenido_extra',
                'type' => 'checkbox',
                'display_name' => 'Columna extra?',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sí","off":"No","display":{"width":2}}',
                'order' => 26,
            ),
            91 => 
            array (
                'id' => 138,
                'data_type_id' => 8,
                'field' => 'columnas_extra',
                'type' => 'number',
            'display_name' => 'Ancho (entre 1 y 6)',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:6"},"display":{"width":2}}',
                'order' => 27,
            ),
            92 => 
            array (
                'id' => 139,
                'data_type_id' => 8,
                'field' => 'posicion_extra',
                'type' => 'select_dropdown',
                'display_name' => 'Posición en la página',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"izquierda","options":{"izquierda":"Izquierda","derecha":"Derecha"},"display":{"width":2}}',
                'order' => 28,
            ),
            93 => 
            array (
                'id' => 140,
                'data_type_id' => 8,
                'field' => 'pastilla_id',
                'type' => 'hidden',
                'display_name' => 'Pastilla Id',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 29,
            ),
            94 => 
            array (
                'id' => 141,
                'data_type_id' => 8,
                'field' => 'pagina_belongsto_pastilla_relationship',
                'type' => 'relationship',
                'display_name' => 'Banner en contenido',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Pastilla","table":"pastillas","type":"belongsTo","column":"pastilla_id","key":"id","label":"nombre","pivot_table":"calendario","pivot":"0","taggable":"0"}',
                'order' => 30,
            ),
            95 => 
            array (
                'id' => 142,
                'data_type_id' => 10,
                'field' => 'enlace',
                'type' => 'text',
                'display_name' => 'Enlace',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":12}}',
                'order' => 12,
            ),
            96 => 
            array (
                'id' => 143,
                'data_type_id' => 10,
                'field' => 'destino_enlace',
                'type' => 'select_dropdown',
                'display_name' => 'Destino Enlace',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Por defecto":"Por defecto","Popup":"Pop-up","Nuevo":"Ventana/pestaña nueva"},"display":{"width":4}}',
                'order' => 13,
            ),
            97 => 
            array (
                'id' => 144,
                'data_type_id' => 3,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"user_roles","pivot":"1"}',
                'order' => 11,
            ),
            98 => 
            array (
                'id' => 145,
                'data_type_id' => 15,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            99 => 
            array (
                'id' => 146,
                'data_type_id' => 15,
                'field' => 'pagina_id',
                'type' => 'hidden',
                'display_name' => 'Pagina Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            100 => 
            array (
                'id' => 147,
                'data_type_id' => 15,
                'field' => 'pastilla_id',
                'type' => 'hidden',
                'display_name' => 'Pastilla Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            101 => 
            array (
                'id' => 148,
                'data_type_id' => 15,
                'field' => 'orden',
                'type' => 'hidden',
                'display_name' => 'Orden',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            102 => 
            array (
                'id' => 149,
                'data_type_id' => 15,
                'field' => 'texto',
                'type' => 'rich_text_box',
                'display_name' => 'Texto',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            103 => 
            array (
                'id' => 150,
                'data_type_id' => 15,
                'field' => 'texto_cabecera',
                'type' => 'text',
                'display_name' => 'Cabecera / Título',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            104 => 
            array (
                'id' => 151,
                'data_type_id' => 15,
                'field' => 'enlace',
                'type' => 'text',
                'display_name' => 'Enlace',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":8}}',
                'order' => 7,
            ),
            105 => 
            array (
                'id' => 152,
                'data_type_id' => 15,
                'field' => 'destino_enlace',
                'type' => 'select_dropdown',
                'display_name' => 'Destino Enlace',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Por defecto":"Por defecto","Popup":"Pop-up","Nuevo":"Ventana/pestaña nueva"},"display":{"width":4}}',
                'order' => 8,
            ),
            106 => 
            array (
                'id' => 153,
                'data_type_id' => 15,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            107 => 
            array (
                'id' => 154,
                'data_type_id' => 15,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 10,
            ),
            108 => 
            array (
                'id' => 155,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            109 => 
            array (
                'id' => 156,
                'data_type_id' => 17,
                'field' => 'menu_item_id',
                'type' => 'hidden',
                'display_name' => 'Menu Item Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            110 => 
            array (
                'id' => 157,
                'data_type_id' => 17,
                'field' => 'pagina_id',
                'type' => 'hidden',
                'display_name' => 'Pagina Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            111 => 
            array (
                'id' => 158,
                'data_type_id' => 17,
                'field' => 'orden',
                'type' => 'hidden',
                'display_name' => 'Orden',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            112 => 
            array (
                'id' => 159,
                'data_type_id' => 17,
                'field' => 'texto',
                'type' => 'text',
                'display_name' => 'Texto',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            113 => 
            array (
                'id' => 160,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            114 => 
            array (
                'id' => 161,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            115 => 
            array (
                'id' => 162,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            116 => 
            array (
                'id' => 163,
                'data_type_id' => 19,
                'field' => 'partesgrafica_id',
                'type' => 'hidden',
                'display_name' => 'Partesgrafica Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            117 => 
            array (
                'id' => 164,
                'data_type_id' => 19,
                'field' => 'slider_id',
                'type' => 'hidden',
                'display_name' => 'Slider Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            118 => 
            array (
                'id' => 165,
                'data_type_id' => 19,
                'field' => 'orden',
                'type' => 'hidden',
                'display_name' => 'Orden',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            119 => 
            array (
                'id' => 166,
                'data_type_id' => 19,
                'field' => 'titulo',
                'type' => 'text',
                'display_name' => 'Título diapositiva',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            120 => 
            array (
                'id' => 167,
                'data_type_id' => 19,
                'field' => 'texto',
                'type' => 'text',
                'display_name' => 'Texto diapositiva',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            121 => 
            array (
                'id' => 168,
                'data_type_id' => 19,
                'field' => 'texto_align',
                'type' => 'select_dropdown',
                'display_name' => 'Alineación del texto',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default": "Left","options":{"Left":"Izquierda","Center":"Centro","Right":"Derecha"},"display":{"width":6}}',
                'order' => 7,
            ),
            122 => 
            array (
                'id' => 169,
                'data_type_id' => 19,
                'field' => 'texto_color',
                'type' => 'color',
                'display_name' => 'Color del texto',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6}}',
                'order' => 8,
            ),
            123 => 
            array (
                'id' => 170,
                'data_type_id' => 19,
                'field' => 'boton_texto',
                'type' => 'text',
                'display_name' => 'Texto del botón',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            124 => 
            array (
                'id' => 171,
                'data_type_id' => 19,
                'field' => 'boton_color',
                'type' => 'color',
                'display_name' => 'Color del texto del botón',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6}}',
                'order' => 10,
            ),
            125 => 
            array (
                'id' => 172,
                'data_type_id' => 19,
                'field' => 'boton_bgcolor',
                'type' => 'color',
                'display_name' => 'Color de fondo del botón',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":6}}',
                'order' => 11,
            ),
            126 => 
            array (
                'id' => 173,
                'data_type_id' => 19,
                'field' => 'posicion_elementos',
                'type' => 'select_dropdown',
                'display_name' => 'Posición de los elementos',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"1":"Arriba Izquierda","2":"Arriba Centro","3":"Arriba Derecha","4":"Abajo Izquierda","5":"Abajo Centro","6":"Abajo Derecha"}}',
                'order' => 12,
            ),
            127 => 
            array (
                'id' => 174,
                'data_type_id' => 19,
                'field' => 'enlace',
                'type' => 'text',
                'display_name' => 'Enlace',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":8}}',
                'order' => 13,
            ),
            128 => 
            array (
                'id' => 175,
                'data_type_id' => 19,
                'field' => 'destino_enlace',
                'type' => 'select_dropdown',
                'display_name' => 'Destino Enlace',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Por defecto":"Por defecto","Popup":"Pop-up","Nuevo":"Ventana/pestaña nueva"},"display":{"width":4}}',
                'order' => 14,
            ),
            129 => 
            array (
                'id' => 176,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 15,
            ),
            130 => 
            array (
                'id' => 177,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 16,
            ),
            131 => 
            array (
                'id' => 178,
                'data_type_id' => 20,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            132 => 
            array (
                'id' => 179,
                'data_type_id' => 20,
                'field' => 'partesgrafica_id',
                'type' => 'hidden',
                'display_name' => 'Partesgrafica Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            133 => 
            array (
                'id' => 180,
                'data_type_id' => 20,
                'field' => 'pastilla_id',
                'type' => 'hidden',
                'display_name' => 'Pastilla Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            134 => 
            array (
                'id' => 181,
                'data_type_id' => 20,
                'field' => 'orden',
                'type' => 'hidden',
                'display_name' => 'Orden',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            135 => 
            array (
                'id' => 182,
                'data_type_id' => 20,
                'field' => 'texto',
                'type' => 'text',
                'display_name' => 'Texto',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            136 => 
            array (
                'id' => 183,
                'data_type_id' => 20,
                'field' => 'texto_cabecera',
                'type' => 'text',
                'display_name' => 'Cabecera / Título',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            137 => 
            array (
                'id' => 184,
                'data_type_id' => 20,
                'field' => 'enlace',
                'type' => 'text',
                'display_name' => 'Enlace',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":8}}',
                'order' => 7,
            ),
            138 => 
            array (
                'id' => 185,
                'data_type_id' => 20,
                'field' => 'destino_enlace',
                'type' => 'select_dropdown',
                'display_name' => 'Destino Enlace',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"Por defecto":"Por defecto","Popup":"Pop-up","Nuevo":"Ventana/pestaña nueva"},"display":{"width":4}}',
                'order' => 8,
            ),
            139 => 
            array (
                'id' => 186,
                'data_type_id' => 20,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            140 => 
            array (
                'id' => 187,
                'data_type_id' => 20,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 10,
            ),
        ));
        
        
    }
}